# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: Features & Bug Fixes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - logistics
          - tests
          - documentation
    - title: Documentation
      labels:
        - documentation
    - title: Development
      labels:
        - logistics
        - tests
    - title: Dependencies
      labels:
        - dependencies
