__version__ = '1.9.0'
__author__ = 'Oliver King'
__url__ = 'https://github.com/ortk95/planetmapper'
__license__ = 'MIT'
__description__ = 'PlanetMapper: A Python package for visualising, navigating and mapping Solar System observations'
