name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage[toml]
        pip install -r requirements.txt
    - name: Run tests
      continue-on-error: true
      run: |
        python3 -m coverage run -m unittest discover -s tests -v
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2